# Generated by Django 4.2.5 on 2023-10-04 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(default='')),
                ('AHF_diabetes', models.BooleanField(default=False)),
                ('quien_diabetes', models.CharField(default='', max_length=20)),
                ('AHF_hipertension', models.BooleanField(default='')),
                ('quien_hipertension', models.CharField(default='', max_length=20)),
                ('AHF_dislipidemias', models.BooleanField(default=False)),
                ('quien_dislipidemias', models.CharField(default='', max_length=20)),
                ('AP_diabetes_mellitus', models.BooleanField(default=False)),
                ('AP_hipertension', models.BooleanField(default=False)),
                ('AP_dislipidemias', models.BooleanField(default=False)),
                ('problema_gastrointestinales', models.BooleanField(default=False)),
                ('cual_problema_gastrointestinal', models.CharField(default='', max_length=100)),
                ('observaciones_patologicas', models.TextField(default='')),
                ('intervencion_quirurgica', models.BooleanField(default='')),
                ('cual_intervencion_quirurgica', models.CharField(default='', max_length=70)),
                ('alergia_alimento', models.BooleanField(default=False)),
                ('cual_alergia_alimento', models.CharField(default='', max_length=50)),
                ('consume_farmaco_alergia', models.BooleanField(default=False)),
                ('cual_alergia_farmaco', models.CharField(default=False, max_length=50)),
                ('desde_cuando_farmaco', models.CharField(default='', max_length=40)),
                ('realiza_actividad_fisica', models.BooleanField(default=False)),
                ('cual_actividad_fisica', models.CharField(default='', max_length=50)),
                ('duracion', models.CharField(default='', max_length=10)),
                ('consume_alcohol', models.BooleanField(default=False)),
                ('consume_tabaco', models.BooleanField(default=False)),
                ('consume_droga', models.BooleanField(default=False)),
                ('numero_gestas', models.PositiveIntegerField(default='', null=True)),
                ('numero_partos_cesarea', models.PositiveIntegerField(default='', null=True)),
                ('numero_abortos', models.PositiveIntegerField(default='', null=True)),
                ('actualmente_lactando', models.BooleanField(default=False, null=True)),
                ('fecha_ultima_menstruacion', models.DateField(default=None, null=True)),
                ('presenta_menoupasia', models.BooleanField(default=False)),
                ('frecuencia_cereales', models.CharField(default='', max_length=5)),
                ('frecuencia_frutas', models.CharField(default='', max_length=5)),
                ('frecuencia_verduras', models.CharField(default='', max_length=5)),
                ('frecuencia_carne_roja', models.CharField(default='', max_length=5)),
                ('frecuencia_pollo', models.CharField(default='', max_length=5)),
                ('frecuencia_lacteos', models.CharField(default='', max_length=5)),
                ('frecuencia_leguminosas', models.CharField(default='', max_length=5)),
                ('frecuencia_azucar', models.CharField(default='', max_length=5)),
                ('frecuencia_grasas', models.CharField(default='', max_length=5)),
                ('frecuencia_pescado', models.CharField(default='', max_length=5)),
                ('cuantas_veces_come', models.PositiveIntegerField(default='')),
                ('quien_prepara_alimentos', models.CharField(default='', max_length=30)),
                ('litro_consume_agua', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('litro_consume_refresco', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('litro_consume_cafe', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('alimentos_causan_malestar', models.TextField(default='')),
                ('tipo_grasa_preparar_alimentos', models.CharField(default='', max_length=30)),
                ('diagnostico_nutricio', models.TextField(default='')),
                ('tratamiento_nutricional', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=45)),
                ('apePaterno', models.CharField(default='', max_length=45)),
                ('apeMaterno', models.CharField(default='', max_length=45)),
                ('edad', models.PositiveIntegerField(default='')),
                ('estado_civil', models.CharField(default='', max_length=15)),
                ('CURP', models.CharField(default='', max_length=18)),
                ('escolaridad', models.CharField(default='', max_length=20)),
                ('colonia', models.CharField(default='', max_length=45)),
                ('calle', models.CharField(default='', max_length=45)),
                ('numero_exterior', models.PositiveIntegerField(default='')),
                ('referencia', models.TextField(default='')),
                ('CP', models.PositiveIntegerField(default='')),
                ('telefono', models.CharField(default='', max_length=10)),
                ('derecho_habiencia', models.CharField(default='', max_length=9)),
                ('unidad_salud', models.CharField(default='', max_length=150)),
                ('ultima_visita_medico', models.DateField(default=None, null=True)),
                ('numero_personas_vive', models.PositiveIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField(default=None, null=True)),
                ('hora_cita', models.TimeField(default='')),
                ('especialidad', models.CharField(default='', max_length=12)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_dsm.paciente')),
            ],
        ),
    ]
