# Generated by Django 4.2.5 on 2023-09-23 01:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=45)),
                ('apePaterno', models.CharField(default='', max_length=45)),
                ('apeMaterno', models.CharField(default='', max_length=45)),
                ('edad', models.PositiveIntegerField(default='')),
                ('estado_civil', models.CharField(default='', max_length=15)),
                ('CURP', models.CharField(default='', max_length=18)),
                ('escolaridad', models.CharField(default='', max_length=20)),
                ('colonia', models.CharField(default='', max_length=45)),
                ('calle', models.CharField(default='', max_length=45)),
                ('numero_exterior', models.PositiveIntegerField(default='')),
                ('referencia', models.TextField(default='')),
                ('CP', models.PositiveIntegerField(default='')),
                ('derecho_habiencia', models.CharField(default='', max_length=9)),
                ('unidad_salud', models.CharField(default='', max_length=150)),
                ('ultima_visita_medico', models.DateField(default='')),
                ('programa_gobierno_federal', models.BooleanField(default=False)),
                ('programa_gobierno_estatal', models.BooleanField(default=False)),
                ('programa_gobierno_municipal', models.BooleanField(default=False)),
                ('numero_personas_vive', models.PositiveIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hoja_evaluacion_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(default=datetime.date.today)),
                ('tension_arterial', models.PositiveSmallIntegerField(default='')),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(default='')),
                ('frecuencia_respiratoria', models.PositiveSmallIntegerField(default='')),
                ('temperatura', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('saturacion_oxigeno', models.PositiveSmallIntegerField(default='')),
                ('glucosa', models.PositiveSmallIntegerField(default='')),
                ('peso', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('talla', models.CharField(default='', max_length=50)),
                ('cintura', models.PositiveSmallIntegerField(default='')),
                ('especialista', models.CharField(default='', max_length=100)),
                ('nota_medica', models.TextField(default='')),
                ('archivo_medico', models.FileField(blank=True, null=True, upload_to='archivos_medicos/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_dsm.paciente')),
            ],
        ),
    ]
