# Generated by Django 4.2.5 on 2023-10-19 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
