# Generated by Django 4.2.5 on 2023-10-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_enfermeria',
            name='alcoholismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nota_enfermeria',
            name='practica_ejercicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nota_enfermeria',
            name='tabaquismo',
            field=models.BooleanField(default=False),
        ),
    ]
