# Generated by Django 4.2.5 on 2023-10-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichapsicologicaadulto',
            old_name='historia_acutual_paciente',
            new_name='historia_actual_paciente',
        ),
    ]
