# Generated by Django 4.2.5 on 2023-10-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
