# Generated by Django 4.2.5 on 2023-10-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0002_alter_nota_enfermeria_alcoholismo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField(default=False)),
                ('checkbox2', models.BooleanField(blank=True, default=False, null=True)),
                ('texto', models.CharField(default='', max_length=50)),
                ('texto2', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
