# Generated by Django 4.2.5 on 2023-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0002_evento_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='evento',
            name='nom_evento',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='evento',
            name='notas',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
