# Generated by Django 4.2.5 on 2023-10-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0002_rename_historia_acutual_paciente_fichapsicologicaadulto_historia_actual_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapsicologicaniño',
            name='informacion_hermanos',
            field=models.TextField(default='', null=True),
        ),
    ]
