# Generated by Django 4.2.5 on 2023-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0003_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinicaNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(default='')),
                ('AHF_diabetes', models.BooleanField(default=False)),
                ('quien_diabetes', models.CharField(default='', max_length=20)),
                ('AHF_hipertension', models.BooleanField(default='')),
                ('quien_hipertension', models.CharField(default='', max_length=20)),
                ('AHF_dislipidemias', models.BooleanField(default=False)),
                ('quien_dislipidemias', models.CharField(default='', max_length=20)),
                ('AP_diabetes_mellitus', models.BooleanField(default=False)),
                ('AP_hipertension', models.BooleanField(default=False)),
                ('AP_dislipidemias', models.BooleanField(default=False)),
                ('problemas_gastroinstestinales', models.BooleanField(default=False)),
                ('cual_problema_gastrointestinal', models.CharField(default='', max_length=30)),
                ('observaciones_patologicas', models.TextField(default='')),
                ('intervencion_quirurgica', models.BooleanField(default=False)),
                ('cual_intervencion_quirurgica', models.CharField(default='', max_length=30)),
                ('alergia_alimento', models.BooleanField(default=False)),
                ('cual_alergia_alimento', models.CharField(default='', max_length=40)),
                ('alergia_farmaco', models.BooleanField(default=False)),
                ('cual_alergia_farmaco', models.CharField(default='', max_length=40)),
                ('desde_cuando_farmaco', models.DateField(default='')),
                ('realiza_actividad_fisica', models.BooleanField(default=False)),
                ('cual_actividad_fisica', models.CharField(default='', max_length=30)),
                ('duracion', models.TimeField(default='')),
                ('consume_alcohol', models.BooleanField(default=False)),
                ('consume_tabaco', models.BooleanField(default=False)),
                ('consume_droga', models.BooleanField(default=False)),
                ('frecuencia_cereales', models.CharField(default='', max_length=5)),
                ('frecuencia_frutas', models.CharField(default='', max_length=5)),
                ('frecuencia_verduras', models.CharField(default='', max_length=5)),
                ('frecuencia_carne_roja', models.CharField(default='', max_length=5)),
                ('frecuencia_pollo', models.CharField(default='', max_length=5)),
                ('frecuencia_lacteos', models.CharField(default='', max_length=5)),
                ('frecuencia_leguminosas', models.CharField(default='', max_length=5)),
                ('frecuencia_azucar', models.CharField(default='', max_length=5)),
                ('frecuencia_grasas', models.CharField(default='', max_length=5)),
                ('frecuencia_pescado', models.CharField(default='', max_length=5)),
                ('cuantas_veces_come', models.PositiveIntegerField(default='')),
                ('quien_prepara_alimentos', models.CharField(default='', max_length=30)),
                ('litro_consume_agua', models.DecimalField(decimal_places=2, default='', max_digits=3)),
                ('litro_consume_refresco', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('litro_consume_cafe', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('alimentos_causan_malestar', models.TextField(default='')),
                ('tipo_grasa_preparar_alimentos', models.CharField(default='', max_length=18)),
            ],
        ),
    ]
