# Generated by Django 4.2.5 on 2023-10-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0003_alter_fichapsicologicaniño_informacion_hermanos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapsicologicaniño',
            name='descripcion_viven_con_niño',
            field=models.TextField(default='', null=True),
        ),
    ]
