# Generated by Django 4.2.5 on 2023-10-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0003_remove_evento_descripcion_evento_nom_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaevaluacionclinica',
            name='imagenRecetaMedica',
            field=models.ImageField(null=True, upload_to='recetasMedicas'),
        ),
    ]
