# Generated by Django 4.2.5 on 2023-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0003_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ultima_visita_medico',
            field=models.DateField(default=None, null=True),
        ),
    ]
