# Generated by Django 4.2.5 on 2023-09-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0004_historiaclinicanutricion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoriaClinicaNutricion',
            new_name='HistoriaNutricion',
        ),
    ]
