# Generated by Django 4.2.5 on 2023-10-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0004_hojaevaluacionclinica_imagenrecetamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaevaluacionclinica',
            name='imagenRecetaMedica',
            field=models.ImageField(blank=True, null=True, upload_to='recetasMedicas'),
        ),
    ]
