# Generated by Django 4.2.5 on 2023-09-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0005_remove_paciente_programa_gobierno_estatal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(default='', max_length=12),
        ),
    ]
