# Generated by Django 4.2.5 on 2023-10-23 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0005_alter_hojaevaluacionclinica_imagenrecetamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fechaRegistro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
