# Generated by Django 4.2.5 on 2023-11-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0006_paciente_fecharegistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenmedico',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='oxigenacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='peso_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='temperatura',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
