# Generated by Django 4.2.5 on 2023-09-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0006_cita_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
    ]
