# Generated by Django 4.2.5 on 2023-11-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0007_examenmedico_frecuencia_respiratoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenmedico',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examenmedico',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examenmedico',
            name='oxigenacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examenmedico',
            name='temperatura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examenmedico',
            name='tension_arterial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
