# Generated by Django 4.2.5 on 2023-11-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0008_alter_examenmedico_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenmedico',
            name='frecuencia_respiratoria',
        ),
    ]
