# Generated by Django 4.2.5 on 2023-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0009_alter_prueba_numero_alter_prueba_numero2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='numero',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='numero2',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
