# Generated by Django 4.2.5 on 2023-11-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0009_remove_examenmedico_frecuencia_respiratoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenmedico',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
