# Generated by Django 4.2.5 on 2023-11-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0010_examenmedico_frecuencia_respiratoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gestion_dsm.usuario'),
            preserve_default=False,
        ),
    ]
