# Generated by Django 4.2.5 on 2023-10-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0011_alter_prueba_numero_alter_prueba_numero2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default='')),
                ('lugar', models.CharField(default='', max_length=60)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gestion_dsm.usuario')),
            ],
        ),
    ]
