# Generated by Django 4.2.5 on 2023-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_dsm', '0012_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nom_evento',
            field=models.CharField(default='', max_length=60),
        ),
    ]
